sudo: required
language: node_js
node_js:
  - "7"
branches:
  only:
    - dev
    - master
services:
  - docker
notifications:
  email:
    recipients:
      - ernest@unstable.build
script: scripts/test.sh
